spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:h2:mem:coupondb
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true


springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.show-actuator=false

logging.level.it.schwarz.jobs.review.coupon=DEBUG
logging.level.org.springframework.web=DEBUG